language: java
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.m2

services:
- docker

before_script:
- docker --version

script:
- make docker-build
- make test

after_script:
- docker images