language: java
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.m2

services:
- docker

jobs:
  include:
    - stage: commit stage
      script:
      - make docker-build
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker tag maven-docker-pipeline:latest $DOCKER_USERNAME/maven-docker-pipeline:pending
      - docker push $DOCKER_USERNAME/maven-docker-pipeline:pending
      - git tag -a $TRAVIS_BUILD_NUMBER -m "Travis CI build #$TRAVIS_BUILD_NUMBER"
      - git push origin --tags
    - stage: acceptance testing
      script:
      - docker pull $DOCKER_USERNAME/maven-docker-pipeline:pending
      - docker tag $DOCKER_USERNAME/maven-docker-pipeline:pending maven-docker-pipeline:latest
      - make test
    - stage: promote image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker pull $DOCKER_USERNAME/maven-docker-pipeline:pending
      - docker tag $DOCKER_USERNAME/maven-docker-pipeline:pending $DOCKER_USERNAME/maven-docker-pipeline:latest
      - docker tag $DOCKER_USERNAME/maven-docker-pipeline:pending $DOCKER_USERNAME/maven-docker-pipeline:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/maven-docker-pipeline:latest

notifications:
  email:
    on_success: change
    on_failure: always